py/access/access/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('timeclock.urls')),
]

py/access/timeclock/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from timeclock import views


urlpatterns = [
    url(r'^$', login_required(views.index)),
    url(r'^reports/$', login_required(views.reports)),
    url(r'^sms/receive/$', views.sms_receive),
    path('clockevent/add/', views.ClockEventCreate.as_view(), name='clockevent-add'),
    path('clockevent/update/<int:pk>/', views.ClockEventUpdate.as_view(), name='clockevent-update'),
    path('clockevent/detail/<int:pk>/', views.ClockEventDetail.as_view(), name='clockevent-detail'),
    # path('segment/update/<int:pk>/', views.SegmentUpdate.as_view(), name='segment-update'),
    path('segment/update/<int:pk>/', views.segment_update, name='segment-update'),
    path('segment/detail/<int:pk>/', views.SegmentDetail.as_view(), name='segment-detail'),
    path('segment/delete/<int:pk>/', views.segment_delete, name='segment-delete'),
    path('shift/create/', views.ShiftCreate.as_view(), name='shift-create'),
    path('shift/update/<int:pk>/', views.ShiftUpdate.as_view(), name='shift-update'),
    path('shift/detail/<int:pk>/', views.ShiftDetail.as_view(), name='shift-detail'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='timeclock/login.html'), name='login'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='timeclock/login.html'), name='password_reset'),
    path('export/<slug:s_date>/<slug:e_date>/', views.export_isolved, name='export-isolved'),
    path('sclock/', views.sclock, name="sclock"),
    path('ssn_clock/', views.ssn_clock, name="ssn_clock"),
    path('get_in_emps/', views.get_clockedin_emps, name='get_in_emps'),
    url(r'^admin/', admin.site.urls),
]

py/access/timeclock/models.py
import json
import time
from pytz import timezone
from django.utils import timezone as dj_tz
from decimal import Decimal
from datetime import date, datetime, timedelta
from django.utils.translation import ugettext as _
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models import Q  #, F, Max, Min, Count, Sum, Avg
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
from cryptography.hazmat.primitives import serialization as crypto_serialization, hashes
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.backends import default_backend as crypto_default_backend
from cryptography.hazmat.primitives.serialization import load_pem_private_key, load_pem_public_key
from twilio.rest import Client
from server import actions as a
from server.models import BaseModel, TimeClock, Person, Log

EST = timezone('US/Eastern')
# Create your models here.

account_sid = 'AC78206534f90af3a363f9e6bbaa522a3e'
auth_token = '89472df5af87ff4473d62b7f667bf919'
ME = '+17173569858'


class ClockEvent(BaseModel):
    time_clock = models.ForeignKey(TimeClock, on_delete=models.CASCADE)
    employee = models.ForeignKey(Person, on_delete=models.CASCADE)
    date_time = models.DateTimeField(null=True, blank=True)
    adjustment = models.BooleanField(default=False)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return '{0} via {1} at {2}'.format(self.employee, self.time_clock, self.date_created)

    def serialize(self):
        return { 
            'time_clock': self.time_clock.id,
            'employee': self.employee.id,
            'date_time': self.date_time
        }


class Shift(BaseModel):
    employee = models.ForeignKey(Person, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.employee, self.date)

    def total_time_data(self):
        x = sum([d.duration() for d in self.segment_set.all()], timedelta(0,0))
        return x

    def total_time(self):
        return time.strftime('%H:%M:%S', time.gmtime(self.total_time_data().seconds))

    def serialize(self):
        segs = {}
        for s in self.segment_set.all():
            ti = dj_tz.localtime(s.time_in).strftime('%I:%M %p')
            to = dj_tz.localtime(s.time_out).strftime('%I:%M %p') if s.time_out else ''
            segs[s.id] = '{0} - {1}'.format(ti, to)
        return {
            'shift_id': self.id,
            'employee_id': self.employee.id,
            'employee_name': self.employee.first_name + ' ' + self.employee.last_name,
            'segments': segs
        }

    def get_absolute_url(self):
        return reverse('shift-detail', kwargs={'pk': self.pk})


class Segment(BaseModel):
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE)
    clock_in = models.ForeignKey(ClockEvent, null=True, on_delete=models.CASCADE, related_name='segment_in')
    time_in = models.DateTimeField(null=True, blank=True)
    clock_out = models.ForeignKey(ClockEvent, on_delete=models.SET_NULL, null=True, blank=True, related_name='segment_out')
    time_out = models.DateTimeField(null=True, blank=True)
    adjusted = models.BooleanField(default=False, editable=False)
    adjusted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, editable=False)

    def __str__(self):
        return '{0} -- In: {1}, Out: {2}'.format(self.clock_in.employee, self.time_in, self.time_out)

    def save(self, *args, **kwargs):
        if self.clock_in and not self.time_in:
            self.time_in = self.clock_in.date_time
        if self.clock_out and not self.time_out:
            self.time_out = self.clock_out.date_time 
        super(Segment, self).save(*args, **kwargs)
       
    def duration(self):
        now = dj_tz.localtime()
        try:
            if self.time_in and self.time_out:
                end_time = self.time_out
            elif self.time_in.date() == now.date():
                end_time = now
            else:
                d = self.time_in.date()
                end_time = datetime(d.year, d.month, d.day, 23, 59, 59, 0, EST)
            return end_time - self.time_in
        except Exception as e:
            log = Log.objects.create(message=str(e))
        return timedelta(days=1)

    def serialize(self):
        return {
            'segment_id': self.id,
            'employee_id': self.shift.employee.id,
            'employee_name': self.shift.employee.first_name + ' ' + self.shift.employee.last_name,
            'clock_in_id': self.clock_in.id,
            'time_in': dj_tz.localtime(self.time_in).strftime('%Y-%m-%dT%H:%M'),
            'clock_out_id': self.clock_out.id if self.clock_out else '',
            'time_out': dj_tz.localtime(self.time_out).strftime('%Y-%m-%dT%H:%M') if self.time_out else ''
        }


class AdminLeave(BaseModel):
    description = models.TextField(null=True, blank=True)
    date = models.DateField()
    include_active = models.BooleanField(default=False, help_text='Add all clocked in employees.')
    employees = models.ManyToManyField(Person, blank=True, limit_choices_to={'active': True})
    hours = models.DecimalField(max_digits=5, decimal_places=2, help_text='Hours to fill to.')

    def __str__(self):
        return str(self.date)

    def employee_count(self):
        return self.employees.all().count()


class SMSMessage(BaseModel):
    sender = models.CharField(max_length=100)
    recipient = models.CharField(max_length=100, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    sid = models.CharField(max_length=255, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)


def lt(t):
    """ Default time zone application and string formatting of time object t """
    return dj_tz.localtime(t).strftime('%I:%M %p')


def sms_send(sms):
    client = Client(account_sid, auth_token)
    message = client.messages.create(
        body=sms.body,
        from_=sms.sender,
        to=sms.recipient
    )
    sms.id = message.sid
    return sms


@receiver(post_save, sender=ClockEvent)
def link_ce_to_segment(sender, instance, created, *args, **kwargs):
    if created and not instance.adjustment:  # not for manual adjustments
        active_segments = Segment.objects.filter(clock_out__isnull=True, clock_in__employee=instance.employee, date_created__date=dj_tz.localdate())
        if active_segments.exists():
            active_segment = active_segments[0]
            active_segment.clock_out = instance
            active_segment.save()
            msg = 'You have clocked OUT at {0}.'.format(lt(active_segment.time_out))
        else:
            shift, created = Shift.objects.get_or_create(employee=instance.employee, date=dj_tz.localdate())
            segment = Segment(
                shift=shift,
                clock_in=instance
            )
            segment.save()
            msg = 'You have clocked IN at {0}.'.format(lt(segment.time_in))
        sms = SMSMessage.objects.create(
            sender=ME,
            recipient=instance.employee.phone,
            body=msg
        )
        sms_send(sms)
    else:
        # update any linked segments
        segs = Segment.objects.filter(clock_in=instance)
        if segs.exists():
            segs[0].time_in = instance.date_time
            segs[0].save()
        else:
            segs = Segment.objects.filter(clock_out=instance)
            if segs.exists():
                segs[0].time_out = instance.date_time
                segs[0].save()

py/access/templates/timeclock/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/img/favicon.ico">

    <title>MP Time Machine</title>

    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.datetimepicker.min.css"/>
    <!-- open-iconic fonts -->
    <link href="/static/icons/font/css/open-iconic-bootstrap.min.css" rel="stylesheet">
    <link href="/static/icons/font/css/open-iconic.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/styles.css" rel="stylesheet">
    <style>
      main { padding-top: 50px; }
    </style>
    {% block media %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">MP Time Machine</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated %}
           <li class="nav-item">
            <a class="nav-link" href="/reports/">Reporting</a>
          </li>{% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}
      {% endblock %}
    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/vendor/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/jquery.datetimepicker.full.min.js"></script>
  </body>
</html>

py/access/templates/timeclock/dialog.html
<div class="modal fade" id="segmentModal" tabindex="-1" role="dialog" aria-labelledby="segmentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="segmentModalLabel">Time Edit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          {% csrf_token %}
          <input type="hidden" name="shift_id" id="id_shift_id"/>
          <input type="hidden" name="employee_id" id="id_employee_id"/>
          <input type="hidden" name="clock_in_id" id="id_clock_in_id"/>
          <input type="hidden" name="clock_out_id" id="id_clock_out_id"/>
          <div class="form-group">
            <label for="id_time_in" class="col-form-label">Clock In:</label>
            <input type="text" class="form-control" name="time_in" id="id_time_in">
          </div>
          <div class="form-group">
            <label for="id_time_out" class="col-form-label">Clock Out:</label>
            <input type="text" class="form-control" name="time_out" id="id_time_out">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save Segment</button>
      </div>
    </div>
  </div>
</div>

py/access/templates/timeclock/index.html
{% extends 'timeclock/base.html' %}

      {% block media %}
      <script type="text/javascript">
        $(function() {
          $('#id_date').datetimepicker({
              format: 'Y-m-d',
              timepicker: false,
              lang: 'en',
              onChangeDateTime: function(dp, $input) {
                  console.log($input.val())
                  $('#date_form').submit();
              }
          });

          $('#cal-icon').click(function() {
              $('#id_date').datetimepicker('show');
          });

          $('#shiftCreateBtn').click(function(e) {
            var modal = $('#shiftCreateModal');
            const data = new URLSearchParams(new FormData(document.getElementById('shiftCreateForm')));
            console.log(data);
            fetch('/shift/create/', {
              method: 'POST',
              credentials: 'include',
              headers: { "X-CSRFToken": data.get('csrfmiddlewaretoken') },
              body: data
            }).then(function(response) { return response.json(); }).then(function(j) {
              console.log(j);
              var btn = `<button id="shift-btn-${j.shift_id}" data-toggle="modal" data-target="#shiftModal" data-shift-id="${j.shift_id}" style="visibility: hidden;">&nbsp;</button>`;
              console.log(btn);
              $('body').append(btn);
              $(`#shift-btn-${j.shift_id}`).click();
              //redirect to shiftModal... create new button, click it, and delete the button?
            });
            modal.modal('hide');
          });

          $('#segmentBtn').click(function(e) {
            var modal = $('#segmentModal');
            const data = new URLSearchParams(new FormData(document.getElementById('segmentForm')));
            console.log(data);
            fetch('/segment/update/' + data.get('segment_id') + '/', {
              method: 'POST',
              credentials: 'include',
              headers: { "X-CSRFToken": data.get('csrfmiddlewaretoken') },
              body: data
            }).then(function(response) { return response.json(); }).then(function(j) {
              $('#id_segments').html(formatSegments(j.segments));
            });
            modal.modal('hide');
          });

          $('#shiftModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var shift_id = button.data('shift-id'); 
            var modal = $(this);
            fetch('/shift/detail/' + shift_id + '/',
              { credentials: 'same-origin' }
            ).then(function(response) {
              return response.json();
            }).then(function(data) {
              console.log(data);
              modal.find('.modal-title').text('Edit shift for ' + data.employee_name);
              modal.find('.modal-body #id_shift_id').val(data.shift_id);
              modal.find('.modal-body #id_employee_id').val(data.employee_id);
              modal.find('.modal-body #id_segments').html(formatSegments(data.segments));
            });
          });

          $('#shiftModal').on('click', '.segDelBtn', function() {
            var segment_id = $(this).data('segment-id');
            fetch('/segment/delete/' + segment_id + '/',
              { credentials: 'same-origin' }
            ).then(function(response) {
              return response.json();
            }).then(function(data) {
              console.log(data);
              $(`#div-segment-${segment_id}`).remove();
            });
          });

          $('#shiftCreateModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var shift_id = button.data('shift-id'); 
            var modal = $(this);
          });

          $('#segmentModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var segment_id = button.data('segment-id'); 
            var modal = $(this);
            fetch('/segment/detail/' + segment_id + '/',
              { credentials: 'same-origin' }
            ).then(function(response) {
              return response.json();
            }).then(function(data) {
              console.log(data);
              modal.find('.modal-title').text('Edit segment for ' + data.employee_name);
              modal.find('.modal-body #id_segment_id').val(data.segment_id);
              modal.find('.modal-body #id_employee_id').val(data.employee_id);
              modal.find('.modal-body #id_clock_in_id').val(data.clock_in_id);
              modal.find('.modal-body #id_clock_out_id').val(data.clock_out_id);
              modal.find('.modal-body #id_time_in').val(data.time_in);
              modal.find('.modal-body #id_time_out').val(data.time_out);
            });
          });

        });

        function formatSegments(segs) {
          var output = '';
          var times = '', ce_id = '', action = '';
          Object.keys(segs).forEach(function(key, index) {
            times = segs[key];
            seg_id = key;
            action = 'Edit';
            var t = `<p><div id="div-segment-${seg_id}" style="width: 420px; height: 32px;">${times} <button data-segment-id="${seg_id}" style="float: right; margin-left: 10px;" class="btn btn-danger segDelBtn"><span class="oi oi-trash"></span></button>&nbsp;<button type="button" style="float: right;" class="btn btn-primary" data-toggle="modal" data-target="#segmentModal" data-segment-id="${seg_id}">${action}</button>&nbsp;&nbsp;</div></p>`;
            output += t;
          });
          return output;
        }

      </script>
      {% endblock %}

      {% block content %}
      <div class="home-page">
        <h1>MP Time Machine</h1>
        <p class="lead">Employee activity on {{ cur_date|date:"l, N j" }}. &nbsp;
            <span class="oi" data-glyph="calendar" id="cal-icon" title="calendar" aria-hidden="true" style="font-size: 75%"></span><form action="" id="date_form" method="post">{% csrf_token %}<input type="text" style="border: 0; position: absolute; width: 1px; height: 1px; top: 145px;" value="{{ cur_date|date:"Y-m-d" }}"" id="id_date" name="date"/></form>
        </p>
        <div class="row">
          <div class="col-md-8 offset-2">
            <p class="lead"><a href="" class="btn btn-info">All</a>&nbsp; {% for d in departments %}<a href="" class="btn btn-default">{{ d }}</a> {% endfor %}</p>
          </div>
          <div class="col-md-2">
            <button class="btn btn-dark" data-toggle="modal" data-target="#shiftCreateModal"><span class="oi oi-plus"></span>&nbsp; Add Shift</button>
          </div>
        </div>
        <div class="row">
          <table class="table table-striped table-sm">
            <thead>
              <th>Employee</th>
              <th>Clocked In</th>
              <th>Clocked Out</th>
              <th>Hours Worked</th>
              <th>Edit</th>
            </thead>
            <tbody>
              {% for s in shifts %}
              <tr>
                <td>{{ s.employee.first_name }} {{ s.employee.last_name }}</td>
                {% with f=s.segment_set.all.first l=s.segment_set.all.last %}
                <td>{{ f.time_in }}</td>
                <td>{% if l.time_out %}{{ l.time_out }}{% endif %}</td>
                {% endwith %}
                <td>{{ s.total_time }}</td>
                <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#shiftModal" data-shift-id="{{ s.id }}">Edit</button></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      <div class="modal fade" id="shiftCreateModal" tabindex="-1" role="dialog" aria-labelledby="shiftCreateModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="shiftCreateModalLabel">Add Shift</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="shiftCreateForm">
                {% csrf_token %}
                <div class="form-group row">
                  <label for="id_employee" class="col-2 col-form-label">Employee</label>
                  <div class="col-10">
                    <select class="form-control autocomplete" type="text" id="id_employee" name="employee">
                      <option value="">-- Select an Employee --</option>
                      {% for e in employees %}<option value="{{ e.id }}">{{ e.last_name }}, {{ e.first_name }}</option>{% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group row">
                  <label for="id_date" class="col-2 col-form-label">Date</label>
                  <div class="col-10">
                    <input class="form-control" type="date" id="id_date" name="date">
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="shiftCreateBtn">Add Shift</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="shiftModal" tabindex="-1" role="dialog" aria-labelledby="shiftModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="shiftModalLabel">Shift Edit</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form>
                {% csrf_token %}
                <input type="hidden" name="shift_id" id="id_shift_id"/>
                <input type="hidden" name="employee_id" id="id_employee_id"/>
              </form>
              <div id="id_segments">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="segmentModal" tabindex="-1" role="dialog" aria-labelledby="segmentModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="segmentModalLabel">Segment Edit</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="segmentForm">
                {% csrf_token %}
                <input type="hidden" name="segment_id" id="id_segment_id"/>
                <input type="hidden" name="employee_id" id="id_employee_id"/>
                <input type="hidden" name="clock_in_id" id="id_clock_in_id"/>
                <input type="hidden" name="clock_out_id" id="id_clock_out_id"/>
                <div class="form-group row">
                  <label for="id_time_in" class="col-2 col-form-label">Time In</label>
                  <div class="col-10">
                    <input class="form-control" type="datetime-local" id="id_time_in" name="time_in">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="id_time_out" class="col-2 col-form-label">Time Out</label>
                  <div class="col-10">
                    <input class="form-control" type="datetime-local" id="id_time_out" name="time_out">
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="segmentBtn">Save Segment</button>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}

py/access/templates/timeclock/login.html
{% extends 'timeclock/base.html' %}

{% block content %}
<script>$(function() {
    $('#id_loginform').find('input[type=text],input[type=password]').addClass('form-control');
});</script>
<div class="row">
    <div class="col-md-5">
        <p><b>User Login</b></p>
        <form method="post" action="/sclock/" id="id_sclock_form">
            {% csrf_token %}
            <div class="form-group">
                <label for="user_id">User ID:</label>
                <input type="password" class="form-control" name="user_id" id="id_user_id"/>
            </div>
            <input type="submit" class="btn btn-default" value="login">
        </form>
    </div>
    <div class="col-md-5 offset-md-2">
        <p><b>Admin Login</b></p>

        <form method="post" action="{% url 'login' %}" id="id_loginform">
        {% csrf_token %}
            <div class="form-group">
                {{ form.username.label_tag }}
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.password.label_tag }}
                {{ form.password }}
            </div>
            <input type="submit" class="btn btn-default" value="login">
            <input type="hidden" name="next" value="{{ next }}">
        </form>

        {# Assumes you setup the password_reset view in your URLconf #}
        <p><a href="{% url 'password_reset' %}">Lost password?</a></p>
    </div>
</div>
{% endblock %}

py/access/templates/timeclock/reports.html
{% extends 'timeclock/base.html' %}

      {% block media %}
      <script type="text/javascript">
        $(function() {
            $('#id_start').datetimepicker({
                format: 'Y-m-d',
                timepicker: false,
                lang: 'en',
            });
            $('#id_end').datetimepicker({
                format: 'Y-m-d',
                timepicker: false,
                lang: 'en',
            });
            $('#exportBtn').click(function() {
              // redirect to export url with start and end dates
              var start_date = $('#id_start').val();
              var end_date = $('#id_end').val();
              var url = `/export/${start_date}/${end_date}/`;
              window.location.href = url;
            });
        });
      </script>
      {% endblock %}
      {% block content %}
      <div class="home-page">
        <h1>MP Time Machine</h1>
        <p class="lead">Employee activity from: </p>
        <div class="row">
          <div class="col-md-7 offset-md-3">
          <form action="" id="date_form" method="post" class="form-inline">
              {% csrf_token %}
              <input type="text" class="form-control" placeholder="start date" value="{{ start|date:"Y-m-d" }}" id="id_start" name="start"/> &nbsp;
            thru &nbsp;
              <input type="text" class="form-control" placeholder="end date" value="{{ end|date:"Y-m-d" }}" id="id_end" name="end"/> &nbsp;
              &nbsp; <input type="submit" class="btn btn-dark" value="Fetch!">
          </form>
          </div>
        </div>
        <div class="row" style="padding-top: 10px;">
          <div class="col-md-8 offset-2">
            <p class="lead"><a href="" class="btn btn-info">All</a>&nbsp; {% for d in departments %}<a href="" class="btn btn-default">{{ d }}</a> {% endfor %}</p>
          </div>
          <div class="col-md-2">
            <button class="btn btn-primary" id="exportBtn"><span class="oi oi-cloud-download"></span>&nbsp; Export</button>
          </div>
        </div>
        <div class="row">
          <table class="table table-striped table-sm">
            <thead>
              <th>Employee</th>
              <th>Date/Time In</th>
              <th>Date/Time Out</th>
              <th>Hours Worked</th>
            </thead>
            <tbody>
              {% for s in shifts %}
              <tr>
                <td>{% ifchanged s.employee %}{{ s.employee.first_name }} {{ s.employee.last_name }}{% endifchanged %}</td>
                {% with f=s.segment_set.all.first l=s.segment_set.all.last %}
                <td {% if not l.time_out %}class="warning"{% endif %}>{{ f.time_in }}</td>
                <td>{% if l.time_out %}{{ l.time_out }}{% endif %}</td>
                {% endwith %}
                <td>{% if s.total_time_data.seconds < 43200 %}{{ s.total_time }}{% else %}<span class="warning">{{ s.total_time }}</span>{% endif %}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% endblock %}